path_log = "/home/wikmgg/Documents/GitHub/access.log"
path_user = "/home/wikmgg/Documents/GitHub/user/"
path = "/home/wikmgg/Documents/GitHub/"
chat_id = "############"
token = "######################################"