path_log = "/home/wikmgg/Documents/GitHub/test.log"
path_user = "/home/wikmgg/Documents/GitHub/user/"
path = "/home/wikmgg/Documents/GitHub/"
chat_id = "############"
token = "######################################"