path_log = "/home/wikmgg/Documents/GitHub/Xray-Log-Analyzer/access.log"
#path_log = "/root/Xray-Log-Analyzer/access.log"
path_user = "/home/wikmgg/Documents/GitHub/Xray-Log-Analyzer/user/"
#path_user = "/root/Xray-Log-Analyzer/user/"
path = "/home/wikmgg/Documents/GitHub/Xray-Log-Analyzer/"
#path = "/root/Xray-Log-Analyzer/"
origin_path_log = "/var/lib/marzban/log/access.log"
chat_id = "877591460"
token = "6386634380:AAGdHDGK3hmoo5vh2IRj3w0Ntgb47XAoZhQ"
# token = '6386634380:AAGdHDGK3hmoo5vh2IRj3w0Ntgb47XAoZhQ'
# chat_id = '877591460'
cpu_threshold = 60
ram_threshold = 60